### PR TITLE
Main ian- Handle admin and customer routes #7

### PR DESCRIPTION
**Pull request by Ian-arap-kirui**
initial commit: handle admin and customer routes #7

### CODE REVIEW

**Comment by Ian-arap-kirui** [comment]
Okay, thank you for the heads up on good practices

**Comment by msunji** [comment]
To add to Gibson's comment, it would be helpful to add a short description about what your PR does. This gives the reviewer/s a bit more context to work with. For instance, you may want to add a quick bit about the changes you've made.

**Comment by Ranjeetk489** [comment]
hey ian a suggestion on how you could structure your pull request.-
 files to review-
- implemented this feature
- these routes are functioning
- these routes are for view only and further features will be implemented soon

here's deployment URL -vercel/netlify

**Comment by Ranjeetk489** [comment]
Went through some of your files and wow, really appreciate the work you have done. I see that you have implemented sidebar and nav as well?  That issue was assigned to me 😅

**Pull request closed without merging**
